version: '3'

services:
  keycloak:
    image: test-keycloak:latest
    command: ["start", "--optimized"]
    environment:
      - KC_FEATURES_DISABLED=admin2
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KC_HTTP_ENABLE=true
      - KC_PROXY=edge
      - KEYCLOAK_ADMIN_PASSWORD=admin=value
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - apache
    networks:
      - keycloak_network

  postgres:
    image: test-postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  apache:
    image: test-apache:latest
    ports:
      - "443:443"
    networks:
      - keycloak_network


networks:
  keycloak_network:

volumes:
  postgres_data: