version: '3'

services:
  keycloak:
    build:
      context: ./test-keycloak
      dockerfile: Dockerfile
    image: test-keycloak:latest
    command: ["start", "--optimized"]
    environment:
      - KC_FEATURES_DISABLED=admin2
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme #change to desired password
      - KC_HTTP_ENABLE=true
      - KC_PROXY=edge
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - keycloak_network

  postgres:
    build:
      context: ./test-postgres
      dockerfile: Dockerfile
    image: test-postgres:latest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  apache:
    build:
      context: ./test-apache
      dockerfile: Dockerfile
    image: test-apache:latest
    ports:
      - "443:443"
    networks:
      - keycloak_network


networks:
  keycloak_network:

volumes:
  postgres_data: