# Use an official PostgreSQL as the base image
FROM postgres:15

# Set environment variables for PostgreSQL
ENV POSTGRES_DB keycloak
ENV POSTGRES_USER keycloak
ENV POSTGRES_PASSWORD keycloak

# Expose PostgreSQL port
EXPOSE 5432